### ISSUE TITLE
Custom error message for a struct field that already has "json" in go gin

### ISSUE THREAD

**Issue by LimitlessDonald** [golodash/galidator#7] opened 2023-08-18 21:36 UTC
**Describe the bug**
Hello, first of all, thank you for your code and how much work you put into it, its really helpful 

I am using go gin , so I am extracting the error message from the struct according to your documentation . 

``` 
type SettingsUpdatable struct {
	MainTheme                  string `json:"mainTheme" binding:"omitempty"` // theme name, for later, when we have multiple themes
	Theme                      string `json:"theme" binding:"omitempty"`
	DefaultWeightUnit          string `json:"defaultWeightUnit" binding:"required,oneof=kg lb" required:"RequiredField" oneof:"InvalidValue"`
	DefaultLength              string `json:"defaultLength" binding:"required,oneof=m ft" required:"RequiredField" oneof:"InvalidValue"`
	DefaultWidthUnit           string `json:"defaultWidthUnit" binding:"required,oneof=m ft" required:"RequiredField" oneof:"InvalidValue"`
	DefaultLandMeasurementUnit string `json:"defaultLandMeasurementUnit" binding:"required,oneof=square-foot acre hectare" required:"RequiredField" oneof:"InvalidValue"`
	DefaultVolumeUnit          string `json:"defaultVolumeUnit" binding:"required,oneof=L us-liquid-gal imperial-gal cubic-foot bu" required:"RequiredField" oneof:"InvalidValue"`
	DefaultHeightUnit          string `json:"defaultHeightUnit" binding:"required,oneof=m ft" required:"RequiredField" oneof:"InvalidValue"`
	DefaultTempUnit            string `json:"defaultTempUnit" binding:"required,oneof=C F" required:"RequiredField" oneof:"InvalidValue"`
	ActiveMenu                 string `json:"activeMenu" binding:"omitempty,json"  c.json:"InvalidJSON"`
	ActiveServices             string `json:"activeServices" binding:"omitempty,json" c.json:"InvalidJSON"`
	DashWidgets                string `json:"dashWidgets" binding:"omitempty,json" c.json:"InvalidJSON"`
	}

```

I get the error message for invalid/incorrect fields that validation  : 

```	
"errors": {
		"activeMenu": "activeMenu",
		"activeServices": "activeServices",
		"dashWidgets": "dashWidgets",
		"facebookLink": "InvalidURL",
		"footerLink": "InvalidURL"
               }

```

**Expected behavior**

```	
"errors": {
		"activeMenu": "InvalidJSON",
		"activeServices": "InvalidJSON",
		"dashWidgets": "InvalidJSON",
		"facebookLink": "InvalidURL",
		"footerLink": "InvalidURL"
               }

```
For the fields that have **json** validation, how can I add a tag for the preferred error message ? Looking forward to your response. Thanks.

**Comment by maktoobgar** [comment] 2023-08-19 07:48
Hi,
Thanks for using this tool.

First let's create a testing environment and fix a little mistake in your struct definition tags:

```
package main

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/golodash/galidator"
)

type SettingsUpdatable struct {
	MainTheme                  string `json:"mainTheme" binding:"omitempty"` // theme name, for later, when we have multiple themes
	Theme                      string `json:"theme" binding:"omitempty"`
	DefaultWeightUnit          string `json:"defaultWeightUnit" binding:"required,oneof=kg lb" required:"RequiredField" oneof:"InvalidValue"`
	DefaultLength              string `json:"defaultLength" binding:"required,oneof=m ft" required:"RequiredField" oneof:"InvalidValue"`
	DefaultWidthUnit           string `json:"defaultWidthUnit" binding:"required,oneof=m ft" required:"RequiredField" oneof:"InvalidValue"`
	DefaultLandMeasurementUnit string `json:"defaultLandMeasurementUnit" binding:"required,oneof=square-foot acre hectare" required:"RequiredField" oneof:"InvalidValue"`
	DefaultVolumeUnit          string `json:"defaultVolumeUnit" binding:"required,oneof=L us-liquid-gal imperial-gal cubic-foot bu" required:"RequiredField" oneof:"InvalidValue"`
	DefaultHeightUnit          string `json:"defaultHeightUnit" binding:"required,oneof=m ft" required:"RequiredField" oneof:"InvalidValue"`
	DefaultTempUnit            string `json:"defaultTempUnit" binding:"required,oneof=C F" required:"RequiredField" oneof:"InvalidValue"`
	ActiveMenu                 string `json:"activeMenu" binding:"omitempty,json" json:"InvalidJSON"`
	ActiveServices             string `json:"activeServices" binding:"omitempty,json" json:"InvalidJSON"`
	DashWidgets                string `json:"dashWidgets" binding:"omitempty,json" json:"InvalidJSON"`
}

var g = galidator.G()
var validator = g.Validator(SettingsUpdatable{})

func main() {
	r := gin.Default()
	r.POST("/", func(c *gin.Context) {
		req := &SettingsUpdatable{}
		if err := c.BindJSON(req); err != nil {
			fmt.Println(err)
			c.JSON(http.StatusOK, gin.H{
				"error":  "error happened",
				"errors": validator.DecryptErrors(err),
			})
		}
	})
	r.Run()
}
```
What I changed in your structure definition tags was that I replaced every `c.json:"<content>"` with `json:"<content>"` because `c` is to get deep into children of a `slice` but your fields are `string` not slice and the problem is obvious now... `json` tag means something else, it means how to represent this field in a `json` but now how we can define a `json` error message?

I'll come back in a few hours with a solution and this will be fixed today.

**Comment by maktoobgar** [comment] 2023-08-19 08:39
Done...
It was easier than I expected.
Use version `v1.3.5`: `go get github.com/golodash/galidator@v1.3.5`
This is the description of this realise:

When changing the error messages of a rule in tag section of a struct element, use `_` at the start of every rule or some rules if they have conflict with another tag which is using for another purpose.
Example:
```go
type Example struct {
	Field string `json:"field" binding:"required,json" _json:"$field is not json"`
}
```
As you can see, `json` tag means something else, so to fix the behavior of the galidator to not use the `json` tag, we use `_json` tag.

And that's it.
Just use `_json` instead of `c.json` tag to fix it.

**Comment by maktoobgar** [comment] 2023-08-19 08:43
I'm gonna close this issue now.
If there was some other bugs, I would be happy to know about them too.
Thanks for the issue.

**Closed by maktoobgar** 2023-08-19 08:43 UTC
